name: Deploy CheckVisit FrontEnd

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t checkvisit-front .

      - name: Run Container
        run: |
          # Para o container antigo se ele existir, mas não trava se não existir
          docker stop checkvisit-front-container || true
          docker rm checkvisit-front-container || true
          
          # Executa o novo container mapeando a porta 3000 da EC2 para a 80 do Nginx
          docker run -d \
            --name checkvisit-front-container \
            --restart always \
            -p 3000:80 \
            checkvisit-front

      - name: Docker System Prune
        run: |
          # Limpeza automática para evitar o erro "No space left on device" no futuro
          docker system prune -f